# config.toml

title = "chat_config"

chat_id = 3001
db_dsn = "mongodb://localhost:27017"
database = "chat"
http_listen_addr = ":8083"

# chat evironment
registry = "mdns"
transport = "tcp"
broker = "nsq"
