# config.toml

title = "mail_config"

debug = true
log_level = "info"

# ip and port
mail_id = 301
http_listen_addr = ":8180"
https_listen_addr = ":453"

# rate limit 服务器每秒可受理最多4000次rpc调用
rate_limit_interval = "0.25ms"
rate_limit_capacity = 4000

# tls config
cert_path_debug = "config/cert/localhost.crt"
key_path_debug = "config/cert/localhost.key"

cert_path_release = "config/cert/localhost.crt"
key_path_release = "config/cert/localhost.key"

# db
db_dsn = "mongodb://localhost:27017"
database = "mail"
redis_addr = "localhost:6379"

# mail evironment 线上环境不能用mdns作为registry，并发高的情况下会出现找不到服务的bug
registry_debug = "mdns"
# registry_address_debug = "localhost:8500"
broker_debug = "http"
# broker_address_debug = "localhost:4150"

registry_release = "consul"
registry_address_release = "host.docker.internal:8500"
broker_release = "nsq"
broker_address_release = "localhost:4150" 
