# config.toml

title = "game_config"

debug = true
log_level = "info"

# ip and port
game_id = 301
account_connect_max = 5000
public_ip = "127.0.0.1"
tcp_listen_addr = ":7030"
websocket_listen_addr = ":445"
http_listen_addr = ":8080"
https_listen_addr = ":4433"

# rate limit 服务器每秒可受理最多4000次rpc调用
rate_limit_interval = "0.25ms"
rate_limit_capacity = 4000

# tls config
cert_path_debug = "config/cert/localhost.crt"
key_path_debug = "config/cert/localhost.key"

cert_path_release = "config/cert/localhost.crt"
key_path_release = "config/cert/localhost.key"

# db
db_dsn = "mongodb://localhost:27017"
database = "game"
redis_addr = "localhost:6379"

# game evironment 线上环境不能用mdns作为registry，并发高的情况下会出现找不到服务的bug
registry_debug = "mdns"
# registry_address_debug = "localhost:8500"
broker_debug = "memory"

registry_release = "consul"
registry_address_release = "localhost:8500"
broker_release = "nsq"
broker_address_release = "localhost:4150" 

# gm
gm_privilege = 3