# config.toml

title = "combat_config"

debug = true
log_level = "info"

# ip and port
combat_id = 201
https_listen_addr = ":447"

# tls config
cert_path_debug = "config/cert/localhost.crt"
key_path_debug = "config/cert/localhost.key"

cert_path_release = "config/cert/hellodudu.crt"
key_path_release = "config/cert/hellodudu.key"

# db
db_dsn = "mongodb://localhost:27017"
database = "db_combat"

# game evironment
registry_debug = "mdns"
broker_debug = "http"

registry_release = "consul"
broker_release = "nsq"
