# config.toml

title = "client_config"

debug = true
log_level = "info"
open_gin = true

client_id = 8001
client_name = "bot1"
heart_beat = "5s"

#prompt ui
prompt_ui = true

# tls config
cert_path_debug = "config/cert/localhost.crt"
key_path_debug = "config/cert/localhost.key"

cert_path_release = "config/cert/hellodudu.crt"
key_path_release = "config/cert/hellodudu.key"

# http
http_listen_addr = ":8082"

gate_endpoints = [
"http://localhost/select_game_addr",
]
